### ISSUE TITLE
Como executar?

### ISSUE THREAD

**Issue by alkabane** [HeitorAugustoLN/GarticCheat#3]
Olá, tem como disponibilizar uma release já compilada? Obrigado desde já!

**Comment by HeitorAugustoLN** [comment]
Opa @alkabane! O cheat ainda está em desenvolvimento. Ainda não temos uma versão estável para entregar aos usuários, mas estamos trabalhando o mais rápido possível para terminar!

Para receber notificações de quando uma versão estável ser lançada marque o "Watch" do canto superior direito da sua tela
